### ISSUE TITLE
Certificados github

### ISSUE THREAD

**Issue by sercuto** [openECOE/openECOE-deploy#1]

**Comment by sercuto** [comment]
Al lanzar el fichero ansible, se queja de los certificados de github, ¿hay que instalar algo previamente?
Gracias

**Comment by TuGeek** [comment]
Si dispones de una clave privada de github en tu equipo, hace una busqueda con "/usr/bin/ssh-keyscan github.com" para insertarla y posteriormente utilizarla para comprobar que tienes permiso para acceder a la rama. Revisamos la recuperación de la clave privada y los permisos necesarios.
