### ISSUE TITLE
Consulta máquina vagrant full

### ISSUE THREAD

**Issue by sercuto** [openECOE/openECOE-deploy#2]
Hola.
He lanzado la máquina virtual full:
vagrant up full

Pero al iniciarla no veo dentro los ficheros de la aplicación, ¿hay que lanzar el ansible e instalarlo todo en ella o usar las máquinas que tienen los modulos por separado?
openECOE-API
openECOE-chrono
openECOE-WebUI-ng

Gracias.

**Comment by TuGeek** [comment]
Hola @sercuto ,

La máquina virtual de vagrant full debe crear la máquina virtual y hacer el provision con ansible por el que recupera los datos de los proyectos de Github y monta las máquinas. Si lo realizas por separado crear una máquina para cada modulo y se comunican entre ellas.

Vamos a revisar el deploy y los permisos necesarios, que puede que sea donde se encuentre el problema.
